[project]
name = "sub2clip"
version = "2.3.3"
description = "Core logic for clip generation"
requires-python = ">=3.10"
dependencies = [
  "pysubs2>=1.8.0",
  "python-ffmpeg>=2.0.12",
  "pillow>=12.1.0"
]

[tool.setuptools.packages.find]
where = ["src"]